config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  resources :docs

  authenticated :user do
    root "docs#index", as: "authenticated_root"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :set_doc, only: [:show, :edit, :update, :destroy]
  before_action :check_user, except: [:index, :new]

  def index
    @docs = Doc.where(user_id: current_user).order(created_at: :desc)
  end

  def show
  end

  def new
    @doc = Doc.new
  end

  def create
    @doc = Doc.new(doc_params)
    @doc.user_id = current_user.id

    if @doc.save
      redirect_to @doc, notice: 'New doc created'
    else
      render 'docs/new', notice: 'There was a problem'
    end
  end

  def edit
  end

  def update
    if @doc.update(doc_params)
      redirect_to @doc, notice: 'Doc updated'
    else
      render 'edit'
    end
  end

  def destroy
    @doc.destroy
    redirect_to docs_path
  end

  private
  def check_user
    redirect_to root_path, notice: "Forbidden action" unless @doc.user_id == current_user.id
  end

  def set_doc
    @doc = Doc.find(params[:id])
  end

  def doc_params
    params.require(:doc).permit(:title, :content, :user_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to docs_path if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
  .mb-3
    = f.input :title, class: 'form-control'
  .mb-3
    = f.input :content, as: :text, input_html: {rows: '10'}, class: 'form-control'
  .mb-3
    = f.submit :submit, class: 'btn btn-primary'
    = link_to 'Cancel', :back, class: 'btn btn-secondary'

app/views/docs/edit.html.haml
.container
  %h1 Edit Doc!
  = render 'form', doc: @doc

app/views/docs/index.html.haml
.container
  #docs.clearfix
    - unless @docs.blank?
      - @docs.each do |doc|
        %a{ href: url_for(doc) }
          .doc
            %p.title= doc.title
            %p.date= time_ago_in_words(doc.created_at)
            %p.content= truncate(doc.content, length: 50)
    - else
      %h2 Create Doc!
      %p Start Creating Documents and Organizing your life!
      %button
        = link_to "Create Doc", new_doc_path, class: 'btn-primary'

app/views/docs/new.html.haml
.container
  %h1 New Doc!
  = render 'form', doc: @doc

app/views/docs/show.html.haml
.container
  #doc_show
    %h1.title= @doc.title
    %p= simple_format(@doc.content)

    .buttons
      = link_to 'Edit', edit_doc_path(@doc), class: 'btn btn-warning'
      = link_to 'Destroy', doc_path(@doc), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

app/views/layouts/application.html.haml
!!!
%html
%head
  %title FileCabinet | Your life's work!
  %meta{name:"viewport", content:"width=device-width,initial-scale=1"}
  = csrf_meta_tags
  = csp_meta_tag
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'

%body
  %header
    .header_inner
      = link_to "FileCabinet", root_path, id: 'logo'

      %nav
        - if user_signed_in?
          = link_to "Create Doc", new_doc_path
          = link_to "Sign Out", destroy_user_session_path, method: :delete
        - else
          = link_to "Log in", new_user_session_path

  %p.notice
    = notice
  %p.alert
    = alert

  = yield

app/views/welcome/index.html.haml
#banner
  .banner_content
    %h1 File Cabinet
    %p Your life's work. Organized. Always.
    %button
      = link_to "Enter", new_user_session_path

#callouts
  .callout_inner
    .wrapper
      .callout
        %h2 Organize
        %p Vestibulum ut eros sed purus tristique fringilla id at purus. Morbi interdum odio tempor fringilla auctor. Phasellus eu erat vel lectus luctus pharetra. Mauris quis tempus sapien, sed dapibus tortor. Phasellus vitae ex sed lacus congue maximus. Aenean at arcu diam. Phasellus rutrum facilisis justo ac imperdiet. Sed rutrum massa vitae erat ultricies, eu elementum elit pellentesque. Fusce id metus posuere, pellentesque diam id, sollicitudin dui. Phasellus semper tellus a volutpat rutrum. Maecenas leo lacus, accumsan a libero quis, efficitur interdum dui. Donec dignissim metus nunc, vitae venenatis ipsum placerat in. Donec id purus egestas, gravida nibh quis, interdum neque. Cras convallis est velit, vel semper tellus tempor quis. Sed pretium convallis maximus. Vivamus risus nibh, gravida eu rhoncus et, elementum nec urna.

#bottom_cta
  .wrapper
    %h2 Go Ahead!
    %br
    %button
      = link_to "Join Now", new_user_registration_path